### ISSUE TITLE
Error in conc step

### ISSUE THREAD

**Issue by minhtrung1997** [lmcai/PhyloHerb#5] opened 2023-06-13 09:52 UTC
I run
```
python /home/ktest/pipeline_env/workflow/PhyloHerb/phyloherb.py -m conc -i Decapoda_mt/Alignment/ -suffix .aln -o phylogeny_cat_decapoda -g gene_order.txt
```
It returns:
```
PhyloHerb v1.1.2
A bioinformatic pipeline for herbariomics based biodiversity research

Concatenate 11 alignments based on the custom gene set

Traceback (most recent call last):
  File "/home/ktest/pipeline_env/workflow/PhyloHerb/phyloherb.py", line 774, in <module>
    concatenation(args.i,files,args.o)
  File "/home/ktest/pipeline_env/workflow/PhyloHerb/phyloherb.py", line 261, in concatenation
    d=AlignIO.convert(output+'.conc.nex', 'nexus', output+'.conc.fas', 'fasta', molecule_type='DNA')
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 474, in convert
    return write(alignments, out_file, out_format)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 220, in write
    for alignment in alignments:
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 473, in <genexpr>
    alignments = (over_ride(_) for _ in alignments)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/AlignIO/__init__.py", line 337, in parse
    yield from i
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/AlignIO/NexusIO.py", line 38, in NexusIterator
    n = Nexus.Nexus(handle)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 668, in __init__
    self.read(input)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 718, in read
    self._parse_nexus_block(title, contents)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 759, in _parse_nexus_block
    getattr(self, "_" + line.command)(line.options)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 1276, in _charpartition
    sub, set_type=CHARSET, separator=":"
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 1295, in _get_indices
    name = self._name_n_vector(opts, separator=separator)
  File "/home/ktest/pipeline_env/software/environment/Trung_conda/PhyloHerb-env/lib/python3.6/site-packages/Bio/Nexus/Nexus.py", line 1320, in _name_n_vector
    raise NexusError("Formatting error in line: %s " % rest)
Bio.Nexus.Nexus.NexusError: Formatting error in line:  phylogeny_cat_decapoda_tem/CDS-cox2.nex: 1-752
```

**Comment by lmcai** [comment] 2023-07-03 01:53
The error is likely caused by special characters in the fasta hearder. A newer version of PhyloHerb v1.1.3 has been released with this bug fixed

**Closed as completed** 2023-07-03 01:55 UTC
